//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloths
    {
        public Cloths()
        {
            this.ProductDetails = new HashSet<ProductDetails>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public byte[] Image { get; set; }
        public string Compound { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<ProductDetails> ProductDetails { get; set; }
    }
}
