//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        public int IdProductsDetail { get; set; }
        public System.DateTime DataEnd { get; set; }
    
        public virtual ProductDetails ProductDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
