//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public ProductDetails()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdCloth { get; set; }
        public int IdFitting { get; set; }
        public int Count { get; set; }
    
        public virtual Cloths Cloths { get; set; }
        public virtual Fittings Fittings { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
